apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-data
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
