apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
