# Default values for fridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# default login vars for postgres
postgresUser: postgres
postgresPass: postgres
postgresDB: fridge

replicaCount: 1

resources:
  requests:
    cpu: 1
    memory: 100Mi
  limits:
    cpu: 2
    memory: 500Mi

usersProbe:
  httpGet:
    path: /api/users/health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 30

host: fridge.localhost

# ofc these values are from me. It is recommended to change them before actually running the app
jwks: |
  {
    "keys":
      [
        {
          "alg": "HS256",
          "key_ops": ["verify"],
          "kty": "oct",
          "k": "bXktbW9zdC1zcGVjaWFsLXNlY3JldC1rZXk="
        }
      ]
  }

dockerConfigJson: |
  {
    "auths": {
      "ghcr.io": {
          "auth": "a3Jpc3RpLWJhbGxhOmdocF9kWWZESTUyN2V0MVJ5WndTU0xOSmQ0d29sRENUTG0yV1EyMWw="
      }
    }
  }
