# Default values for fridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# default login vars for postgres
postgresUser: postgres
postgresPass: postgres
postgresDB: fridge

replicaCount: 1

resources:
  requests:
    cpu: 1
    memory: 100Mi
  limits:
    cpu: 2
    memory: 500Mi

usersProbe:
  httpGet:
    path: /api/users/health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 30

# ofc these values are from me. It is recommended to change them before actually runnig the app
jwks:
  {
    "keys":
      [
        {
          "alg": "HS256",
          "key_ops": ["verify"],
          "kty": "oct",
          "k": "yes, pretty key indeed XD",
        },
      ],
  }

dockerConfigJson: |
  {
    "auths": {
        "ghcr.io": {
            "auth": "hehe lol pls get my creds!"
        }
    }
  }
