import { Recipe } from "@/types/recipeTypes.ts";
import { v4 as uuidv4 } from "uuid";

export const dummyRecipes: Recipe[] = [
    {
        id: uuidv4(),
        title: "Mediterranean Salad with Lemon-Herb Vinaigrette & Feta (Enhanced)",
        description: "This vibrant salad combines the freshness of cucumber and tomato with a simple, ",
        difficulty: "easy",
        cookingTime: 20,
        ingredients: [
            { name: "Salad", quantity: 0, unit: "pcs" },
            { name: "Cucumber", quantity: 0, unit: "pcs" },
            { name: "Tomato", quantity: 3, unit: "pcs" },
            { name: "Oil", quantity: 60, unit: "ml" },
            { name: "Feta Cheese", quantity: 100, unit: "g" },
            { name: "Red Onion", quantity: 0, unit: "pcs" },
            { name: "Fresh Mint", quantity: 15, unit: "g" },
            { name: "Lemon", quantity: 1, unit: "pcs" },
            { name: "Dried Oregano", quantity: 1, unit: "ml" },
            { name: "Black Pepper", quantity: 0, unit: "ml" },
        ],
        instructions: [
            "**Prepare the Tomatoes & Cucumber:** Wash the 3 tomatoes and the cucumber...",
            "**Prepare the Dressing:** In a small bowl or jar, create the vinaigrette...",
            "**Combine & Marinate:** Pour approximately two-thirds of the vinaigrette...",
            "**Add Feta & Mint:** Crumble the feta cheese and sprinkle chopped mint...",
            "**Final Toss & Serve:** Gently toss the salad again and serve immediately...",
        ],
    },
    {
        id: uuidv4(),
        title: "Spicy Tomato & Cucumber Salad with Herbed Oil",
        description: "A vibrant and refreshing salad that balances the sweetness of tomatoes with the ",
        difficulty: "easy",
        cookingTime: 20,
        ingredients: [
            { name: "Salad", quantity: 1, unit: "pcs" },
            { name: "Cucumber", quantity: 0, unit: "pcs" },
            { name: "Tomato", quantity: 3, unit: "pcs" },
            { name: "Oil", quantity: 50, unit: "ml" },
            { name: "Red Onion", quantity: 0, unit: "pcs" },
            { name: "Jalapeño Pepper", quantity: 0, unit: "pcs" },
            { name: "Fresh Cilantro", quantity: 1, unit: "pcs" },
            { name: "Lime", quantity: 1, unit: "pcs" },
            { name: "Smoked Paprika", quantity: 0, unit: "pcs" },
            { name: "Chili Flakes", quantity: 0, unit: "pcs" },
        ],
        instructions: [
            "**Prepare the Tomatoes and Cucumber:** Wash and dice both...",
            "**Prepare the Red Onion:** Peel and finely dice for sharpness...",
            "**Prepare the Jalapeño:** Remove seeds and finely mince...",
            "**Make the Herbed Oil:** Mix oil, jalapeño, and paprika...",
            "**Combine Ingredients:** Mix tomatoes, cucumber, onion...",
            "**Dress the Salad:** Add herbed oil and lime juice...",
            "**Add Freshness:** Add chopped cilantro...",
            "**Season and Adjust:** Taste and tweak seasoning...",
            "**Serve:** Best enjoyed fresh with garnish...",
            "**Extra Tip:** Let sit for 10-15 minutes for flavor melding...",
        ],
    },
    {
        id: uuidv4(),
        title: "Tomato & Cucumber Salad with Dill & Yogurt Dressing",
        description: "A refreshing and simple salad highlighting the freshness of tomatoes and cool,  ",
        difficulty: "easy",
        cookingTime: 15,
        ingredients: [
            { name: "Salad", quantity: 1, unit: "pcs" },
            { name: "Cucumber", quantity: 1, unit: "pcs" },
            { name: "Tomato", quantity: 3, unit: "pcs" },
            { name: "Oil", quantity: 200, unit: "ml" },
            { name: "Greek Yogurt", quantity: 200, unit: "g" },
            { name: "Fresh Dill", quantity: 2, unit: "g" },
            { name: "Lemon", quantity: 0, unit: "pcs" },
            { name: "Garlic", quantity: 1, unit: "pcs" },
            { name: "Salt", quantity: 1, unit: "g" },
            { name: "Black Pepper", quantity: 0, unit: "g" },
        ],
        instructions: [
            "**Prepare the Vegetables:** Wash, slice, and combine cucumber and tomatoes...",
            "**Make the Dressing:** Mix yogurt, garlic, dill, lemon, oil, salt, and pepper...",
            "**Combine & Marinate:** Toss veggies with dressing and chill...",
            "**Serve:** Toss again, adjust seasonings, and serve cold...",
        ],
    },
];
