---
- name: Basic setup
  hosts: all
  become: true
  gather_facts: true
  vars:
    vm_user: admin
  environment:
    ANSIBLE_FORCE_COLOR: "true"
  vars_files:
    - packages.yml
    - keys.yml
    - token.yml
  tasks:
    - name: Add repositories
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        types: [deb]
        uris: "{{ item.uri }}"
        signed_by: "{{ item.key }}"
        suites: ["{{ item.suite }}"]
        components: ["{{ item.component }}"]
        state: present
        enabled: true
      loop: "{{ key_list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        force_apt_get: true

    - name: Login to CR
      # for this, you need a local file called token.yml with the following content:
      # ```yml
      # cr_username: your-github-username
      # token: your-token-with-read-registry-rights
      # ```
      community.docker.docker_login:
        registry: "ghcr.io"
        username: "{{ cr_username }}"
        password: "{{ token }}"
        state: present

    - name: Gimme repo
      ansible.builtin.git:
        repo: https://github.com/AET-DevOps25/team-404-name-not-found.git
        dest: /home/{{ vm_user }}/repo
        version: main

    - name: Setup genai env
      # for this, you need a local file called genai/.env with the following content:
      # ```env
      # OPENAI_API_KEY=your-key
      # OPENAI_API_BASE=https://gpu.aet.cit.tum.de/api
      # ```
      ansible.builtin.copy:
        src: ../../genai/.env
        dest: /home/{{ vm_user }}/repo/genai/.env

    - name: Generate local certificates
      ansible.builtin.command:
        cmd: ./home/{{ vm_user }}/repo/infra/scripts/generate_key_and_cert.sh
      changed_when: false

    - name: Run app
      environment:
        BRANCH: main
      ansible.builtin.command:
        cmd: docker compose -f /home/{{ vm_user }}/repo/compose.yml up
      changed_when: false
