version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./project-words.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - .git
  - node_modules
  - dist
  - build
  - coverage
  - genai/requirements.txt
  - "*.lock"
  - "*.svg"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
