apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: envoy
      # The decision NOT to put this behind the JWT auth logic is 
      # to make it easier for everyone to access the dashboards
      sectionName: https
      namespace: {{ .Values.gatewayNs }}
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: grafana
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /grafana
