apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: envoy
      sectionName: https
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: grafana
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /grafana

# TODO: add the custom pre-made dashboards, see the entire application, host it on their cluster
