apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  annotations:
    ###############################################
    # cert-manager
    cert-manager.io/cluster-issuer: selfsigned
    cert-manager.io/common-name: "404-name-not-found"
    cert-manager.io/subject-organizations: devops
    cert-manager.io/subject-countries: DE
    cert-manager.io/subject-provinces: Bavaria
    cert-manager.io/subject-localities: Munich
    ##############################################
    # nginx
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.host }}/api/users/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: {{ replace "." "-" .Values.host }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
