apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: recipes
spec:
  parentRefs:
    - name: envoy
      sectionName: https
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: recipes
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /api/recipes
