apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: envoy
      sectionName: http
      namespace: {{ .Values.gatewayNs }}
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
