/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllIngredientsForUser"];
        put: operations["alterIngredient"];
        post: operations["saveIngredients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an ingredient by its ID */
        get: operations["getIngredientById"];
        put?: never;
        post?: never;
        delete: operations["deleteIngredient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        Ingredient: {
            id?: string;
            name?: string;
            /** Format: int32 */
            amount?: number;
            /** @enum {string} */
            unit?: "pcs" | "ml" | "g";
            userId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
    getAllIngredientsForUser: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    alterIngredient: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    saveIngredients: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    getIngredientById: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingredient found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"];
                };
            };
            /** @description Ingredient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Ingredient not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Missing user header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "The proxy should have set the user id in the Subject header"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    deleteIngredient: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
