/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllRecipesForUser"];
        put: operations["alterRecipe"];
        post: operations["saveRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/match/{numRecipes}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a recipe using AI from a list of ingredients. The result will try its best to match your given ingredient list */
        post: operations["generateRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/explore/{numRecipes}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a recipe using AI from a list of ingredients. The AI can experiment with your given ingredient list, leading to potential recipes you can't cook right away */
        post: operations["exploreRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by its ID */
        get: operations["getRecipeById"];
        put?: never;
        post?: never;
        delete: operations["deleteRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Ingredient: {
            name?: string;
            /** Format: int32 */
            amount?: number;
            /** @enum {string} */
            unit?: "pcs" | "ml" | "g";
        };
        Recipe: {
            id?: string;
            title?: string;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "advanced";
            /** Format: int32 */
            cookingTime?: number;
            instructions?: string[];
            ingredients?: components["schemas"]["Ingredient"][];
            neededIngredients?: components["schemas"]["Ingredient"][];
            userId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllRecipesForUser: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"][];
                };
            };
        };
    };
    alterRecipe: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"];
                };
            };
        };
    };
    saveRecipe: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"];
                };
            };
        };
    };
    generateRecipe: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path: {
                numRecipes: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"][];
            };
        };
        responses: {
            /** @description Generated Recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"];
                };
            };
        };
    };
    exploreRecipe: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path: {
                numRecipes: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"][];
            };
        };
        responses: {
            /** @description Generated Recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"];
                };
            };
        };
    };
    getRecipeById: {
        parameters: {
            query?: never;
            header?: {
                /** @description User ID from proxy */
                "X-User-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Recipe"];
                };
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Recipe not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Missing user header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "The proxy should have set the user id in the Subject header"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    deleteRecipe: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
