spring:
  application:
    name: images
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/fridge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/images/v1

springdoc:
  api-docs:
    path: /docs/openapi
  swagger-ui:
    path: /docs/swagger-ui.html
    url: /docs/openapi

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: health
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

vars:
  HOST: ${HOST:localhost}
  genai-url: ${GENAI_URL:http://genai:8000/api/genai/v1}
  recipes-url: ${RECIPES_URL:http://recipes:8080/api/recipes}
  ingredients-url: ${INGREDIENTS_URL:http://ingredients:8080/api/ingredients/v1}
  mode: ${MODE:prod}
