# k8s/base/users/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: users
          image: ghcr.io/aet-devops25/team-404-name-not-found/users:main
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres

          # TODO: this fails with a permission denied! Fix it!
          readinessProbe:
            httpGet:
              path: /api/users/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              cpu: 2
              memory: 500Mi
