apiVersion: v1
kind: Secret
metadata:
  name: genai-openai-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  openaiApiKey: {{ .Values.openaiApiKey }}
  openaiApiBase: {{ .Values.openaiApiBase }}
