apiVersion: v1
kind: Secret
metadata:
  name: genai-env-variables
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OPENAI_API_BASE: |-
{{ .Files.Get "genai_api_base" | indent 4 }}
  OPENAI_API_KEY: |-
{{ .Files.Get "genai_api_key" | indent 4 }}
