apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.grafanaUser }}
  password: {{ .Values.grafanaPass }}
