entryPoints:
  web:
    address: ":80"

providers:
  docker:
    network: web
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

experimental:
  plugins:
    jwt:
      moduleName: github.com/tpaulus/jwt-middleware
      version: v1.1.10

api:
  insecure: true

log:
  level: DEBUG
