apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
{{ .Files.Get "datasources.yml" | indent 4 }}
