apiVersion: v1
kind: ConfigMap
metadata:
  name: jvm-grafana-dashboard
  namespace: {{ .Values.namespace }}
  labels:
    grafana_dashboard: "1"
data:
  jvm.json: |
{{ .Files.Get "jvm.json" | indent 4 }}
