apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-grafana-dashboard
  namespace: {{ .Values.namespace }}
  labels:
    grafana_dashboard: "1"
data:
  spring_boot.json: |
{{ .Files.Get "spring_boot.json" | indent 4 }}
