# k8s/base/ui/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      annotations:
        image-deployment: {{now | date "Mon, 02/01/06, 03:04PM"}}
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: client
          image: "ghcr.io/aet-devops25/team-404-name-not-found/client:{{ .Values.currentBranch }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              cpu: 2
              memory: 500Mi
