# k8s/base/ingredients/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredients
  template:
    metadata:
      annotations:
        image-deployment: {{ now | date "Mon, 02/01/06, 03:04PM" }}
      labels:
        app: ingredients
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: ingredients
          image: "ghcr.io/aet-devops25/team-404-name-not-found/ingredients:{{ .Values.currentBranch }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: HOST
              value: {{ .Values.host }}
          startupProbe:
{{ toYaml .Values.ingredientsProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.ingredientsProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.ingredientsProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
