# k8s/base/ui/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      annotations:
        image-deployment: {{now | date "Mon, 02/01/06, 03:04PM"}}
      labels:
        app: ui
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: ui
          # TODO(marcel): when done, replace with ghcr.io/aet-devops25/team-404-name-not-found/users:{{ .Values.currentBranch }}
          image: ealen/echo-server:0.9.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              cpu: 2
              memory: 500Mi
