apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # take your ~/.docker/config.json and put it in the fridge dir as docker_config.json
  .dockerconfigjson: >-
{{ .Files.Get "docker_config.json" | b64enc | indent 4 }}
