apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
{{ .Values.dockerConfigJson | b64enc | indent 4 }}
