apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
spec:
  parentRefs:
    - name: envoy
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: users
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /api/users/whoami
