apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: recipes
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: recipes
  jwt:
    providers:
{{ toYaml .Values.defaultProvider | indent 6 }}
