apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    cert-manager.io/common-name: "404-name-not-found"
    cert-manager.io/subject-organizations: devops
    cert-manager.io/subject-countries: DE
    cert-manager.io/subject-provinces: Bavaria
    cert-manager.io/subject-localities: Munich
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      hostname: fridge.local
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 8443
      hostname: fridge.local
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - name: fridge-local
