# k8s/base/recipes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: recipes
          image: "ghcr.io/aet-devops25/team-404-name-not-found/recipes:{{ .Values.currentBranch }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: HOST
              value: {{ .Values.host }}
          startupProbe:
{{ toYaml .Values.recipesProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.recipesProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.recipesProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
