spring:
  application:
    name: recipes
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/recipes
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
