spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/fridge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      private-key-path: /etc/keys/private.pem
      public-key-path: /etc/keys/public.pem

github:
  client-id: ${CLIENT_ID:Ov23liAV8O5mOpJq1EQ1}
  client-secret: ${CLIENT_SECRET:fd7f9fe6ba42b441acd8a211b24044e08ae65645}
  redirect-uri: https://${HOST:fridge.example}/api/users/callback

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /users
      path-mapping:
        health: health
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
