spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/fridge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET:my-most-special-secret-key}

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /users
      path-mapping:
        health: health
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
