name: Deploy to AET Cluster

on:
  workflow_call:
    secrets:
      KUBECONF:
        required: true
      JWT_PRIV:
        required: true
      JWT_PUB:
        required: true
      DOCKER_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up kubeconfig
      run: |
        echo -e "${{ secrets.KUBECONF }}" | base64 -d > kubeconfig
        mkdir -p ~/.kube
        mv kubeconfig ~/.kube/config

    - name: Set up jwt keys
      run: |
        echo -e "${{ secrets.JWT_PRIV }}" | base64 -d > ${{ github.workspace }}/fridge/private.pem
        echo -e "${{ secrets.JWT_PUB }}" | base64 -d > ${{ github.workspace }}/fridge/public.pem

    - name: Set up docker daemon config
      run: |
        echo -e "${{ secrets.DOCKER_CONFIG }}" | base64 -d > ${{ github.workspace }}/fridge/docker_config.json

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Helm upgrade
      run: |
        helm upgrade --install fridge ${{ github.workspace }}/fridge \
          --namespace team-404-name-not-found \
          --create-namespace \
          -f fridge/values.deploy.yaml
