name: Manual AWS Deployment and Testing

on:
  workflow_dispatch:
    inputs:
      private_key:
        description: 'Private key (PEM) for infra/priv.pem'
        required: true
      AWS_ACCESS_KEY_ID:
        description: 'Key id to access your aws instance'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'Secret key'
        required: true
      AWS_SESSION_TOKEN:
        description: 'Token for your running session'
        required: true
      GHCR_TOKEN:
        description: 'Personal Access Token for the GHCR'
        required: true

jobs:
  deploy-and-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask all secrets
        # if you're bored, think of a way to loop through this
        run: |
          echo "::add-mask::${{ github.event.inputs.private_key }}"
          echo "::add-mask::${{ github.event.inputs.AWS_ACCESS_KEY_ID }}"
          echo "::add-mask::${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}"
          echo "::add-mask::${{ github.event.inputs.AWS_SESSION_TOKEN }}"
          echo "::add-mask::${{ github.event.inputs.GHCR_TOKEN }}"

      - name: Write private key to infra/priv.pem
        run: |
          printf "%s" "${{ github.event.inputs.private_key }}" > infra/priv.pem
          chmod 400 infra/priv.pem

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Install Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "11.6.0"

      - name: Create EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ github.event.inputs.AWS_SESSION_TOKEN }}
        run: |
          cd infra
          make deploy

      - name: Upload Terraform state file
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: infra/terraform.tfstate

      # there also exists ansible.builtin.wait_for_connection, but
      # it doesn't play nice with gather_facts: true, which i need
      # for the docker installation
      - name: Wait for EC2 to be ready
        run: |
          cd infra
          IP=$(terraform output -raw ip)
          echo "Waiting for SSH on $IP..."
          for i in {1..5}; do
            nc -z -v -w5 $IP 22 && echo "SSH is ready!" && exit 0
            echo "Retry $i: SSH not up yet"
            sleep 10
          done
          echo "SSH never became available"
          exit 1

      - name: Debug SSH to EC2
        run: |
          cd infra
          IP=$(terraform output -raw ip)
          ssh -o StrictHostKeyChecking=no -i priv.pem admin@$IP 'echo connected'


      - name: Provision EC2
        run: |
          cd infra
          echo "cr_username: ${{ github.actor }}" >> token.yml
          echo "token: ${{ github.event.inputs.GHCR_TOKEN }}" >> token.yml
          make ansible

      - name: Integration Tests
        run: |
          cd infra
          make ansible PLAYBOOK=tests.yml
