name: Main CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spellcheck:
    uses: ./.github/workflows/spellcheck.yml
  dockerfile_linting:
    uses: ./.github/workflows/dockerfile-linter.yml
