name: Main CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spellcheck:
    uses: ./.github/workflows/spellcheck.yml
  dockerfile_linting:
    name: dockerfile_linting
    uses: ./.github/workflows/dockerfile-linter.yml
  k8s_linting:
    uses: ./.github/workflows/k8s-linter.yml
  ansible-linting:
    uses: ./.github/workflows/ansible-linter.yml
  terraform-linting:
    uses: ./.github/workflows/terraform-lint.yml
  java:
    name: java
    uses: ./.github/workflows/java.yml
  python-formatting:
    name: python-formatting
    uses: ./.github/workflows/python-black-formatting.yml
  typescript:
    name: typescript
    uses: ./.github/workflows/typescript.yml
  docker:
    needs:
      - dockerfile_linting
      - java
    uses: ./.github/workflows/docker.yml
