name: Build and Push Docker Images

on:
  workflow_call:

permissions: write-all

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # this is here to prevent other jobs from running if the triggering event introduced no changes to the corresponding directory
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            services:
              - 'server/**'
              - 'client/**'
              - 'genai/**'
              - '*/docker-bake.hcl'

      - name: Print all environment variables
        run: printenv | sort

      - if: steps.changes.outputs.services == 'true'
        name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.services == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # this is here bc gh actions doesn't allow variable interpolation outside a run block
      - name: Fetch branch name
        run: echo "IMAGE_TAG=$GITHUB_REF" >> $GITHUB_ENV

      - if: steps.changes.outputs.services == 'true'
        name: Build and push images using Bake
        uses: docker/bake-action@v4
        # to avoid confusion (and possible conflicts) with using latest everywhere
        # this sets the tag to the branch that triggered the action
        # that way, we can use image:main as the stable standard
        # i know that using the digest would have been the safest option, but that is an extra step ;)
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          files: docker-bake.hcl
          push: true
