name: Dockerfile Linting

on:
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # this is here to prevent other jobs from running if the triggering event introduced no changes to Dockerfiles
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dockerfile:
              - 'Dockerfile**'

      - if: steps.changes.outputs.dockerfile == 'true'
        name: Lint Dockerfiles
        id: lint-dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*Dockerfile"
          recursive: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: steps.lint-dockerfiles.outcome != 'success' && steps.changes.outputs.dockerfile == 'true'
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.lint-dockerfiles.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;
      
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })