name: Build and Push Docker Images

on:
  workflow_call:
  workflow_run:
    workflows:
      - "dockerfile-linter"
      - "java"
    branches:
      - "*"
    types:
      - "completed"

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images using Bake
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          push: true
