name: Build and Push Docker Images

on:
  workflow_call:

permissions: write-all

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # this is here to prevent other jobs from running if the triggering event introduced no changes to the corresponding directory
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            services:
              - 'server/**'
              - 'client/**'
              - 'genai/**'
              - 'docker-bake.hcl'

      - if: steps.changes.outputs.services == 'true'
        name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.services == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: steps.changes.outputs.services == 'true'
        name: Build and push images using Bake
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          push: true
