name: GenAI Tests

on:
  workflow_call:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            genai:
              - 'genai/**'
              - 'tests/**'
              - 'requirements*.txt'
              - 'pyproject.toml'

      - if: steps.changes.outputs.genai == 'true'
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - if: steps.changes.outputs.genai == 'true'
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - if: steps.changes.outputs.genai == 'true'
        name: Run tests
        run: |
          pytest genai/ tests/ --cov=genai --cov-report=xml

      - if: steps.changes.outputs.genai == 'true'
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

      - if: steps.changes.outputs.genai == 'true' && github.event_name == 'pull_request'
        name: Add coverage comment to PR
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage.xml
          title: GenAI Test Coverage Report
