name: Integrate Docker Compose Services

on:
    workflow_call:
      inputs:
        branch-name:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up genai env variables
        run: |
          echo -e "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" > ${{ github.workspace }}/genai/.env
          echo -e "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ${{ github.workspace }}/genai/.env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        env:
          BRANCH: "${{ inputs.branch-name }}"
        with:
          compose-file: "compose.yml"

      - name: Sleep
        run: |
            sleep 60

      - name: Execute tests in the running services
        run: |
          for service in users recipes images; do
            status=$(docker inspect --format='{{ .State.Health.Status }}' "$service")
            if [ "$status" != "healthy" ]; then
              echo "❌ $service is not healthy (status: $status)"
              docker logs "$service" || true
              exit 1
            else
              echo "✅ $service is healthy"
            fi
          done
