name: Java Linting

on:
  workflow_call:

jobs:
  gradle-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - storage

    steps:
      - uses: actions/checkout@v4

      # Check Java files for each microservice
      - uses: burrunan/gradle-cache-action@v3
        name: Check Java files for ${{ matrix.service }}
        with:
          arguments: check
          save-generated-gradle-jars: false
          build-root-directory: server/${{ matrix.service }}
          gradle-version: wrapper

      # Check build.gradle for each microservice
      - uses: burrunan/gradle-cache-action@v3
        name: Check build.gradle for ${{ matrix.service }}
        with:
          arguments: lintGradle
          save-generated-gradle-jars: false
          build-root-directory: server/${{ matrix.service }}
          gradle-version: wrapper
