name: Java

on:
  workflow_call:

jobs:
  java:
    # the rationale behind putting everything here is to benefit from gradle's caches in the runner
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      # this is here to prevent other jobs from running if the triggering event introduced no changes to the server directory
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            server:
              - 'server/**'

      - if: steps.changes.outputs.server == 'true'
        uses: burrunan/gradle-cache-action@v3
        name: Check all Java files
        with:
          arguments: check
          build-root-directory: server
          save-generated-gradle-jars: false
          gradle-version: current

      - if: steps.changes.outputs.server == 'true'
        uses: burrunan/gradle-cache-action@v3
        name: Check all build.gradle
        with:
          arguments: lintGradle
          build-root-directory: server
          save-generated-gradle-jars: false
          gradle-version: current

      - if: steps.changes.outputs.server == 'true'
        uses: burrunan/gradle-cache-action@v3
        name: Test them all
        with:
          arguments: test
          build-root-directory: server
          save-generated-gradle-jars: false
          gradle-version: current

      - if: steps.changes.outputs.server == 'true'
        uses: burrunan/gradle-cache-action@v3
        name: Generate Test Reports
        with:
          arguments: jacocoTestReport
          build-root-directory: server
          save-generated-gradle-jars: false
          gradle-version: current

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/html/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_ci_if_error: true
