name: Check Kubernetes YAMLs with kube-linter

on:
    workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan yaml files with kube-linter
        uses: stackrox/kube-linter-action@v1.0.7
        id: kube-linter-action-scan
        with:
          directory: manifests
        # The following line prevents aborting the workflow immediately in case your files fail kube-linter checks.
        # This allows the following upload-sarif action to still upload the results to your GitHub repo.
        continue-on-error: false