name: Integration tests with minikube

on:   
  workflow_call:
    secrets:
      KUBECONF:
        required: true
      JWT_PRIV:
        required: true
      JWT_PUB:
        required: true
      DOCKER_CONFIG:
        required: true

jobs:
  minikube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Set up jwt keys
      run: |
        echo -e "${{ secrets.JWT_PRIV }}" | base64 -d > ${{ github.workspace }}/fridge/private.pem
        echo -e "${{ secrets.JWT_PUB }}" | base64 -d > ${{ github.workspace }}/fridge/public.pem

    - name: Set up docker daemon config
      run: |
        echo -e "${{ secrets.DOCKER_CONFIG }}" | base64 -d > ${{ github.workspace }}/fridge/docker_config.json

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Helm upgrade
      run: |
        helm upgrade --install fridge ${{ github.workspace }}/fridge \
          --namespace team-404-name-not-found \
          --create-namespace \
          -f fridge/values.local.yaml

    - name: Wait for readiness
      run: |
        kubectl wait --for=condition=ready pod --all --all-namespaces --timeout=120s