name: Spell Check

on:
  workflow_call:
    inputs:
      files:
        required: false
        type: string
        default: '**/*.{md,txt}'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Documentation Spell Check
        uses: streetsidesoftware/cspell-action@v7
        with:
          files: ${{ inputs.files }}
          config: './cspell.config.yaml'

      - name: Code Spell Check
        uses: crate-ci/typos@v1.32.0
