name: TypeScript

on:
  workflow_call:

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # this is here to prevent other jobs from running if the triggering event introduced no changes to the client directory
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            client:
              - 'client/**'

      - if: steps.changes.outputs.client == 'true'
        uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 22
          cache: 'npm' # automatically caches npm dependencies
          cache-dependency-path: client/package-lock.json

      - if: steps.changes.outputs.client == 'true'
        name: Install dependencies
        working-directory: client
        run: npm ci

      - if: steps.changes.outputs.client == 'true'
        name: Lint
        working-directory: client
        run: npm run lint

      - if: steps.changes.outputs.client == 'true'
        name: Test
        working-directory: client
        run: npm run test
