scrape_configs:
  - job_name: users
    metrics_path: "/api/users/prometheus"
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - "users:8080"
  - job_name: recipes
    metrics_path: "/api/recipes/prometheus"
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - "recipes:8080"
  # - job_name: "envoy"
  #   metrics_path: "/stats/prometheus"
  #   static_configs:
  #     - targets:
  #         - "<envoy-gateway>:19000"
